name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install PyOxidizer
      run: cargo install pyoxidizer
    - name: build binary
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: httpie
        path: ${{ github.workspace }}\build\x86_64-pc-windows-msvc\debug\exe\http.exe
